CREAM   = "#FAF6EE"
RUST    = "#9E1B32"
RUST_LT = "#7C1426"
BROWN   = "#1A1A1A"
SAGE    = "#2C5F2D"
GOLD    = "#C9A84A"
WHITE   = "#FFFFFF"
GRAY    = "#6B6B6B"

BRAND_FONT = "'Playfair Display','Georgia','Times New Roman',serif"
SERIF_FONT = "'Cormorant Garamond','Georgia','Times New Roman',serif"
